In [1]:
#data preprocessing

import numpy as np
from PIL import Image
import glob
import os

ctr = 0
NKI_crops_x = np.zeros((107, 770, 32, 32, 3))
NKI_crops_y = np.zeros((107, 770, 32, 32, 3))
os.chdir("C:\\Users\\Shiv\\Documents\\cs231n project\\EpiStromaTrainingImages\\3002564s3\\NKI_Training")
for file in glob.glob("0.*"):
  img = Image.open(file)
  crop_no = 0
  for i in range(0, np.shape(img)[0] - 32, 32):
    for j in range(0, np.shape(img)[1] - 32, 32):
      img2 = img.crop((j,i,j+32,i+32))
      NKI_crops_x[ctr, crop_no, :, :, :] = img2
      crop_no += 1
  ctr += 1

os.chdir("C:\\Users\\Shiv\\Documents\\cs231n project\\EpiStromaTrainingImages\\3002564s3\\NKI_Training\\labeled")
ctr = 0
for file in glob.glob("*"):
  img = Image.open(file)
  crop_no = 0
  for i in range(0, np.shape(img)[0] - 32, 32):
    for j in range(0, np.shape(img)[1] - 32, 32):
      img2 = img.crop((j,i,j+32,i+32))
      NKI_crops_y[ctr, crop_no, :, :, :] = img2
      crop_no += 1
  ctr += 1

#os.chdir("C:\\Users\\Shiv\\Documents\\cs231n project\\EpiStromaTrainingImages\\3002564s3")
#np.savetxt("NKI_crops_x", NKI_crops_x)
#np.savetxt("NKI_crops_y", NKI_crops_y)

print(NKI_crops_y[0,0,:,:,1])

            

    

[[[   0.    2.   30.]
  [   0.    0.   18.]
  [   8.    0.    0.]
  ..., 
  [   0.   54.    0.]
  [   0.   52.    0.]
  [   0.   59.    0.]]

 [[   0.    0.   18.]
  [   0.    0.   11.]
  [   7.    0.    0.]
  ..., 
  [  52.  219.   54.]
  [  46.  223.   55.]
  [  42.  224.   53.]]

 [[   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]
  ..., 
  [  25.  255.   21.]
  [  14.  249.    7.]
  [  10.  248.    4.]]

 ..., 
 [[   8.    0.    0.]
  [   3.    0.    0.]
  [   0.    4.    0.]
  ..., 
  [  27.  236.   23.]
  [  38.  232.   37.]
  [   9.  246.   16.]]

 [[  11.    0.    0.]
  [   4.    0.    0.]
  [   0.    2.    0.]
  ..., 
  [  23.  239.   14.]
  [  31.  239.   23.]
  [   0.  255.    0.]]

 [[  14.    0.    0.]
  [   6.    0.    0.]
  [   0.    1.    0.]
  ..., 
  [  20.  243.    5.]
  [  23.  246.    7.]
  [   0.  255.    0.]]]


In [9]:
NKI_labels = np.zeros(107,770)

# 

for f in range(0,107):
    for c in range(0,770):
        NKI_labels[f,c] = 
        

print(NKI_crops_y[0,0,1:10,1:10,0])
print(NKI_crops_y[0,0,1:10,1:10,1])
print(NKI_crops_y[0,0,1:10,1:10,2])

[[  0.   7.   8.   3.   0.   0.   0.   0.   8.]
 [  0.   0.   4.   7.   7.   1.   0.   0.   0.]
 [  0.   0.   0.  11.  24.  21.   6.   0.   0.]
 [  0.   0.   0.  10.  29.  34.  20.   0.   0.]
 [  0.   0.   0.   3.  17.  24.  15.  14.   0.]
 [  0.   0.   0.   0.   0.   4.   4.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   3.   1.   0.]
 [  0.   0.   0.   0.   0.   0.  10.  20.  11.]
 [  0.   3.   4.   0.   0.   0.   6.  22.  29.]]
[[  0.   0.   0.   1.   5.   6.   3.   0.   0.]
 [  0.   0.   0.   0.   0.   3.   9.  19.  14.]
 [  6.   5.   1.   0.   0.   0.   4.  12.  15.]
 [  9.   9.   4.   0.   0.   0.   0.   7.  10.]
 [  6.   8.   4.   0.   0.   0.   0.  24.  18.]
 [  1.   3.   4.   3.   0.   0.   0.  10.  25.]
 [  0.   0.   2.   5.   4.   0.   0.   0.  32.]
 [  1.   0.   1.   4.   3.   0.   0.   0.   2.]
 [  2.   0.   0.   0.   0.   0.   0.   0.   0.]]
[[ 11.   0.   0.   0.   0.   0.   5.   9.   9.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   5.]
 [  0.   2.   5.   0.   0.   0.   0.  